bcc32 -DHAVE_CONFIG_H -I. -v -c -oapi.obj api.c
bcc32 -DHAVE_CONFIG_H -I. -v -c -oreader.obj reader.c
bcc32 -DHAVE_CONFIG_H -I. -v -c -oscanner.obj scanner.c
bcc32 -DHAVE_CONFIG_H -I. -v -c -oparser.obj parser.c
bcc32 -DHAVE_CONFIG_H -I. -v -c -oloader.obj loader.c
bcc32 -DHAVE_CONFIG_H -I. -v -c -owriter.obj writer.c
bcc32 -DHAVE_CONFIG_H -I. -v -c -oemitter.obj emitter.c
bcc32 -DHAVE_CONFIG_H -I. -v -c -odumper.obj dumper.c
bcc32 -DHAVE_CONFIG_H -I. -v -c -odelphibridge.obj delphibridge.c
